name: shut_up_and_tweet
description: Tweet Strategy Mangement App

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
  
  firebase_core: "^0.5.0+1"
  firebase_auth_web: ^0.3.1+1
  firebase_auth: "^0.18.0+1"
  cloud_firestore: "^0.14.1+3"

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.0
  awesome_dialog: ^1.2.1
  flutter_slidable: ^0.5.7
  clipboard: ^0.1.2+8
  circular_check_box: ^1.0.4
  flash: ^1.3.1

  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf


  assets:
    - assets/backdrop.png
    - assets/logo_appbar.png